import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../entities/ride_request.dart';
import '../repositories/ride_repository.dart';
import '../../../../core/errors/failures.dart';

class CreateRideRequest {
  final RideRepository repository;

  CreateRideRequest(this.repository);

  Future<String> call({
    required String passengerId,
    required LatLng pickupLocation,
    required LatLng dropoffLocation,
    String? pickupAddress,
    String? dropoffAddress,
    String? passengerName,
  }) async {
    try {
      final rideRequest = RideRequest(
        id: '', // Will be generated by repository
        passengerId: passengerId,
        pickupLocation: pickupLocation,
        dropoffLocation: dropoffLocation,
        status: 'REQUESTED',
        createdAt: DateTime.now(),
        pickupAddress: pickupAddress,
        dropoffAddress: dropoffAddress,
        passengerName: passengerName,
      );

      final rideId = await repository.createRideRequest(rideRequest);
      return rideId;
    } catch (e) {
      throw ServerFailure('Failed to create ride request: ${e.toString()}');
    }
  }
}
